name: Flutter CI

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get

      #- run: flutter analyze


    timeout-minutes: 10

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk --flavor prod -t lib/main.dart --split-per-abi
      - run: flutter build apk --flavor dev -t lib/debug_main.dart --split-per-abi

    timeout-minutes: 10